### ISSUE TITLE
Card disappears on no departures

### ISSUE THREAD

**Issue by timon** [nilstgmd/hvv-card#17]
When there is no departures for a station, the card disappears completely, even if several entities were assigned to the card, and some of them still have departures

My config is:

```yaml
type: custom:hvv-card
entities:
  - sensor.borstelmannsweg_133_departures
  - sensor.schadesweg_departures
```

When the last 530 has departed, the card fails to render
